### ISSUE TITLE
Add AlaSQL Transform task

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-transform#9]
### Feature description

This might be part of core transform tasks. [AlaSQL](https://github.com/AlaSQL/alasql) seems useful and lightweight.

For example, you can download [this CSV file](https://huggingface.co/datasets/kestra/datasets/resolve/main/csv/fruit.csv) and do:

```bash
npm install alasql -g 
alasql 'select * into xlsx("new_fruits.xlsx") from CSV("fruit.csv") where id > 98'
```

This will read a CSV file, perform SQL transformation, and export the output into an Excel file.

Some links:
- playground https://jsfiddle.net/jqk80ard/ 
- getting started https://github.com/alasql/alasql/wiki/Getting-started
- wiki/docs https://github.com/AlaSQL/alasql/wiki 
- CLI reference https://github.com/alasql/alasql/wiki/AlaSQL-CLI 

Trying using it in Node task didn't work for me, not sure why:

```yaml
id: alasql
namespace: myteam

tasks:
  - id: extract
    type: io.kestra.plugin.fs.http.Download
    uri: https://huggingface.co/datasets/kestra/datasets/resolve/main/csv/fruit.csv
    
  - id: alasql
    type: io.kestra.plugin.scripts.node.Commands
    inputFiles:
      data.csv: "{{ outputs.extract.uri }}"
    beforeCommands:
      - npm install -g alasql
    commands:
      - alasql 'select * from CSV("data.csv") where id > 98'
```
